name : Skills-lvl_UP
channels:
  - https://anaconda.org/
  - conda-forge
dependencies:
  - python = 3.9.5
  - requests = 2.26.0
  - selenium = 4.5.0
  - python-chromedriver-binary-106.0.5249
  - pytest